todo_app/urls.py
from django.urls import path
from todo_app import views

urlpatterns = [
    path("", views.ListListView.as_view(), name="index"),
    path("list/<int:list_id>/", views.ItemListView.as_view(), name="list"),
    # CRUD patterns for ToDoLists
    path("list/add/", views.ListCreate.as_view(), name="list-add"),
    path(
        "list/<int:pk>/delete/", views.ListDelete.as_view(), name="list-delete"
    ),
    # CRUD patterns for ToDoItems
    path(
        "list/<int:list_id>/item/add/",
        views.ItemCreate.as_view(),
        name="item-add",
    ),
    path(
        "list/<int:list_id>/item/<int:pk>/",
        views.ItemUpdate.as_view(),
        name="item-update",
    ),
    path(
        "list/<int:list_id>/item/<int:pk>/delete/",
        views.ItemDelete.as_view(),
        name="item-delete",
    ),
]

todo_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo_app.urls")),
]

todo_app/models.py
from django.utils import timezone

from django.db import models
from django.urls import reverse


def one_week_hence():
    return timezone.now() + timezone.timedelta(days=7)


class ToDoList(models.Model):
    title = models.CharField(max_length=100, unique=True)

    def get_absolute_url(self):
        return reverse("list", args=[self.id])

    def __str__(self):
        return self.title


class ToDoItem(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    due_date = models.DateTimeField(default=one_week_hence)
    todo_list = models.ForeignKey(ToDoList, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse(
            "item-update", args=[str(self.todo_list.id), str(self.id)]
        )

    def __str__(self):
        return f"{self.title}: due {self.due_date}"

    class Meta:
        ordering = ["due_date"]

todo_app/views.py
from django.urls import reverse, reverse_lazy

from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import ToDoItem, ToDoList


class ListListView(ListView):
    model = ToDoList
    template_name = "todo_app/index.html"


class ItemListView(ListView):
    model = ToDoItem
    template_name = "todo_app/todo_list.html"

    def get_queryset(self):
        return ToDoItem.objects.filter(todo_list_id=self.kwargs["list_id"])

    def get_context_data(self):
        context = super().get_context_data()
        context["todo_list"] = ToDoList.objects.get(id=self.kwargs["list_id"])
        return context


class ListCreate(CreateView):
    model = ToDoList
    fields = ["title"]

    def get_context_data(self):
        context = super().get_context_data()
        context["title"] = "Add a new list"
        return context


class ItemCreate(CreateView):
    model = ToDoItem
    fields = [
        "todo_list",
        "title",
        "description",
        "due_date",
    ]

    def get_initial(self):
        initial_data = super().get_initial()
        todo_list = ToDoList.objects.get(id=self.kwargs["list_id"])
        initial_data["todo_list"] = todo_list
        return initial_data

    def get_context_data(self):
        context = super().get_context_data()
        todo_list = ToDoList.objects.get(id=self.kwargs["list_id"])
        context["todo_list"] = todo_list
        context["title"] = "Create a new item"
        return context

    def get_success_url(self):
        return reverse("list", args=[self.object.todo_list_id])


class ItemUpdate(UpdateView):
    model = ToDoItem
    fields = [
        "todo_list",
        "title",
        "description",
        "due_date",
    ]

    def get_context_data(self):
        context = super().get_context_data()
        context["todo_list"] = self.object.todo_list
        context["title"] = "Edit item"
        return context

    def get_success_url(self):
        return reverse("list", args=[self.object.todo_list_id])


class ListDelete(DeleteView):
    model = ToDoList
    success_url = reverse_lazy("index")


class ItemDelete(DeleteView):
    model = ToDoItem

    def get_success_url(self):
        return reverse_lazy("list", args=[self.kwargs["list_id"]])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["todo_list"] = self.object.todo_list
        return context

todo_app/templates/base.html
<!-- todo_list/todo_app/templates/base.html -->
<!-- Base template -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--Simple.css-->
    <title>Django To-do Lists</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;500;600;700;800&display=swap"
      rel="stylesheet"
    />
    <style>
      .logo {
        margin: -10px 30px;
        font-family: 'Poppins', sans-serif;
        display: flex;
        justify-content: left;
      }
      .container {
        font-family: 'Poppins', sans-serif;
        display: flex;
        justify-content: center;
        width: 92vw;
      }
    </style>
  </head>

  <body>
    <div class="logo">
      <h1  onclick="location.href='{% url "index" %}'">Django To-do Lists</h1>
    </div>
    <div class="container">
      <div>
        {% block content %} This content will be replaced by different html code
        for each page. {% endblock %}
      </div>
    </div>
  </body>
</html>

todo_app/templates/todo_app/index.html
<!-- todo_list/todo_app/templates/todo_app/index.html -->
{% extends "base.html" %} {% block content %}
<!--index.html-->
<style>
  .title {
    text-align: center;
    margin-left: 10px;
    color: #183a37;
  }
  .list-item {
    background: #6cab75;
    border-radius: 30px 2px;
    width: 25vw;
    padding: 20px 40px;
    color: white;
    letter-spacing: 1px;
    margin: 20px 0px;
  }
  .button {
    margin-left: 25px;
    padding: 10px 30px;
    font-size: 16px;
    font-family: 'Poppins', sans-serif;
    background: rgba(58, 125, 68, 0.1);
    border: 2px solid #0A5315;
    border-radius: 29px;
  }
  .button-container {
    margin-top: 40px;
    display: flex;
    justify-content: center;
  }
</style>
{% if object_list %}
<h1 class="title">all my lists</h1>
{% endif %}
<ul style="list-style-type: none">
  {% for todolist in object_list %}
  <li class="list-item">
    <div role="button" onclick="location.href='{% url "list" todolist.id %}'">
      {{ todolist.title }}
    </div>
  </li>
  {% empty %}
  <h1 class="tittle">You have no lists!</h1>
  {% endfor %}
</ul>
<p class="button-container">
  <input 
    class="button"
    value="Add a new list"
    type="button"
    onclick="location.href='{% url "list-add" %}'"/>
</p>

{% endblock %}

todo_app/templates/todo_app/todo_list.html
<!-- todo_list/todo_app/templates/todo_app/todo_list.html -->
<style>
  .title {
    text-align: center;
    margin-left: 10px;
    color: #183a37;
  }
  .list-item {
    background: #6cab75;
    border-radius: 30px 2px;
    width: 25vw;
    padding: 20px 40px;
    color: white;
    letter-spacing: 1px;
    margin: 20px 0px;
  }
  .button {
    margin-left: 25px;
    padding: 10px 30px;
    font-size: 16px;
    font-family: 'Poppins', sans-serif;
    background: rgba(58, 125, 68, 0.1);
    border: 2px solid #0a5315;
    border-radius: 29px;
  }
  .red {
    background: rgba(125, 58, 58, 0.1);
    border: 2px solid rgb(255, 0, 0);
    border-radius: 29px;
  }
  .button-container {
    margin-top: 40px;
    display: flex;
    justify-content: center;
  }
  .list {
    padding: 10px;
    border-radius: 15px;
  }
</style>
{% extends "base.html" %} {% block content %}
<div>
  <div>
    <div>
      <h1 class="title">Edit list:</h1>
      <h2>{{ todo_list.title|upper}}</h2>
    </div>
    <ul>
      {% for todo in object_list %}
      <li class="list">
        <div>
          <div role="button" 
          onclick="location.href='{% url "item-update" todo_list.id todo.id %}'"> 
          {{ todo.title }} (Due {{ todo.due_date|date:"l, F j" }})
        </div>
      </li>
      {% empty %}
      <p>There are no to-do items in this list.</p>
      {% endfor %}
    </ul>
    <p>
      <input class="button" value="Add a new item" type="button"
      onclick="location.href='{% url "item-add" todo_list.id %}'" /> <input
      class="button red" value="Delete this list" type="button"
      onclick="location.href='{% url "list-delete" todo_list.id %}'" />
    </p>
  </div>
</div>
{% endblock %}

todo_app/templates/todo_app/todoitem_confirm_delete.html
<!-- todo_list/todo_app/templates/todo_app/todoitem_confirm_delete.html -->
{% extends "base.html" %}

{% block content %}

<style>
      .title {
    text-align: center;
    margin-left: 10px;
    color: #183a37;
  }
  .button {
    margin-left: 45px;
    margin-top: 10px;
    padding: 10px 30px;
    font-size: 16px;
    font-family: 'Poppins', sans-serif;
    background: rgba(58, 125, 68, 0.1);
    border: 2px solid #0a5315;
    border-radius: 29px;
  }
  .red {
    background: rgba(125, 58, 58, 0.1);
    border: 2px solid rgb(255, 0, 0);
    border-radius: 29px;
  }
  .buttons {
    margin-top: 25px;
    display: flex;
    justify-content: center;
  }
</style>
<h1 class="title">Delete To-do Item</h1>

<p>Are you sure you want to delete the item: <b>{{ object.title }}</b>
    <p>from the list <i>{{ todo_list.title }}</i>?</p>

    <form method="POST">
        {% csrf_token %}
        <input class="button red" value="Yes, delete." type="submit">
        <input class="button" value="Cancel" type="button" onclick=location.href='{% url "list" todo_list.id %}'; />
    </form>

    {% endblock %}

todo_app/templates/todo_app/todoitem_form.html
<!-- todo_list/todo_app/templates/todo_app/todoitem_form.html -->
{% extends "base.html" %} {% block content %}

<style>
  .title {
    text-align: center;
    margin-left: 10px;
    color: #183a37;
  }
  .button {
    margin-left: 20px;
    margin-top: 20px;
    padding: 10px 30px;
    font-size: 16px;
    font-family: 'Poppins', sans-serif;
    background: rgba(58, 125, 68, 0.1);
    border: 2px solid #0a5315;
    border-radius: 29px;
  }
  .red {
    background: rgba(125, 58, 58, 0.1);
    border: 2px solid rgb(255, 0, 0);
    border-radius: 29px;
  }
  .blue {
    background: rgba(60, 58, 125, 0.1);
    border: 2px solid rgb(0, 17, 200);
    border-radius: 29px;
  }
  label {
    font-weight: 400;
    font-size: 20px;
    margin: 0px 10px;
  }
  #id_title {
    font-family: 'Poppins', sans-serif;
    font-size: 16px;
    padding: 6px 10px;
  }
  #id_description {
    padding: 6px 10px;
    font-family: 'Poppins', sans-serif;
  }
  #id_due_date {
    padding: 6px 10px;
    font-family: 'Poppins', sans-serif;
  }
  #id_todo_list {
    border: 1px solid black;
    font-family: 'Poppins', sans-serif;
  }
  p {
    margin: 40px 0px;
  }
  td {
    padding: 6px;
  }
</style>
<h1 class="title">{{ title }}</h1>
<form method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input class="button blue" value="Cancel" type="button"
  onclick="location.href='{% url "list" todo_list.id %}'">
  {% if object %}
  <input
  class="button red"
    value="Delete this item"
    type="button"
    onclick="location.href='{% url "item-delete" todo_list.id object.id %}'">
  {% endif %}
  <input type="submit" value="Submit" class="button" />
</form>

{% endblock %}

todo_app/templates/todo_app/todolist_confirm_delete.html
<!-- todo_list/todo_app/templates/todo_app/todolist_confirm_delete.html -->
<style>
  .title {
    text-align: center;
    margin-left: 10px;
    color: #183a37;
  }
  .button {
    margin-left: 25px;
    padding: 10px 30px;
    font-size: 16px;
    font-family: 'Poppins', sans-serif;
    background: rgba(58, 125, 68, 0.1);
    border: 2px solid #0a5315;
    border-radius: 29px;
  }
  .red {
    background: rgba(125, 58, 58, 0.1);
    border: 2px solid rgb(255, 0, 0);
    border-radius: 29px;
  }
  .buttons {
    margin-top: 25px;
    display: flex;
    justify-content: center;
  }
</style>
{% extends "base.html" %} {% block content %}

<h1 class="title">Delete List</h1>

<p>Are you sure you want to delete the list <i>{{ object.title }}</i>?</p>

<div class="buttons">
  <div>
    <form method="POST">
      {% csrf_token %}
      <input class="button red" type="submit" value="Yes, delete." />
    </form>
  </div>

  <div>
    <input class="button" value="Cancel" type="button"
    onclick="location.href='{% url "index" %}';">
  </div>
</div>

{% endblock %}

todo_app/templates/todo_app/todolist_form.html
{% extends "base.html" %} {% block content %}
<style>
    .title {
    text-align: center;
    margin-left: 10px;
    color: #183a37;
  }
  .button {
    margin-left: 50px;
    padding: 10px 30px;
    font-size: 16px;
    font-family: 'Poppins', sans-serif;
    background: rgba(58, 125, 68, 0.1);
    border: 2px solid #0A5315;
    border-radius: 29px;
  }
  .red {
    background: rgba(125, 58, 58, 0.1);
    border: 2px solid rgb(255, 0, 0);
    border-radius: 29px;
  }
  label {
    font-size: 24px;
    margin: 0px 10px;
  }
  #id_title {
    font-family: 'Poppins', sans-serif;
    font-size: 16px;
    border-radius: 10px;
    padding: 6px 20px;
  }
  p {
    margin: 40px 0px;
  }
</style>
<h1 class="title">{{ title }}</h3>
<div>
  <div>
    <form method="post">
      {% csrf_token %} {{ form.as_p }}
      <input class="button red" value="Cancel" type="button" onclick="location.href='{% url "index" %}';">
      <input class="button" value="Save" type="submit" />
    </form>
  </div>
</div>

{% endblock %}